services:
  app:
    # Render 会使用你项目中的 Dockerfile 来构建镜像
    build: .
    ports:
      # Render 会使用这个端口来暴露你的服务
      - "8080:8080"
    environment:
      # Render 会自动提供一个 DATABASE_URL 环境变量给你的托管数据库
      # Spring Boot 可以直接使用这个 URL 来配置数据库连接
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      # 激活 'prod' profile，你可以创建一个 application-prod.properties 文件来存放生产环境特定配置
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
